Adjust watermark
Memegle/watermark-detector pull request #23
Opened 2021-05-18 06:59 UTC by Ashleyyyyy567

2021-05-18 19:04 UTC, XueweiYan requested changes

2021-05-18 19:04 UTC, XueweiYan commented on watermark_generator/random_image_generator.py
> +        if random() > 0.25: # Random half
图片形式的水印似乎不会出现在正下方或者正中间，所以这里不需要改这个random

2021-05-18 19:04 UTC, XueweiYan commented on watermark_generator/random_image_generator.py
> +            (0, 0, 0, 0)
这里的意思是把所有字换成黑色吗，感觉水印白色比较多？

2021-05-28 18:45 UTC, XueweiYan approved these changes

2021-06-12 04:46 UTC, vinovo commented
@Ashleyyyyy567 @XueweiYan 这个PR没问题的话就merge了吧？

2021-06-14 23:13 UTC, merged